---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: brianbyers/concourse-gradle
    tag: "latest"

inputs:
  - name: user-service-git

outputs:
  - name: artifact-dir

run:
  path: user-service-git/ci/scripts/build-artifact.sh
