---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: brianbyers/concourse-gradle
    tag: "latest"

inputs:
  - name: user-service-git

run:
  path: user-service-git/ci/scripts/unit-test.sh
